export const formations = {
  '4-4-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'ST', position: 'ST', row: 3 },
    { label: 'ST', position: 'ST', row: 3 }
  ],
  '4-3-3': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'AML', position: 'AML', row: 3 },
    { label: 'ST', position: 'ST', row: 3 },
    { label: 'AMR', position: 'AMR', row: 3 }
  ],
  '3-5-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'ST', position: 'ST', row: 3 },
    { label: 'ST', position: 'ST', row: 3 }
  ],
  '4-2-3-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'DMC', position: 'DMC', row: 2 },
    { label: 'DMC', position: 'DMC', row: 2 },
    { label: 'AML', position: 'AML', row: 3 },
    { label: 'AMC', position: 'AMC', row: 3 },
    { label: 'AMR', position: 'AMR', row: 3 },
    { label: 'ST', position: 'ST', row: 4 }
  ],
  '4-5-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'ST', position: 'ST', row: 3 }
  ],
  '3-4-3': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'AML', position: 'AML', row: 3 },
    { label: 'ST', position: 'ST', row: 3 },
    { label: 'AMR', position: 'AMR', row: 3 }
  ],
  '5-3-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'WBL', position: 'WBL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'WBR', position: 'WBR', row: 1 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'ST', position: 'ST', row: 3 },
    { label: 'ST', position: 'ST', row: 3 }
  ],
  '4-1-4-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'DMC', position: 'DMC', row: 2 },
    { label: 'ML', position: 'ML', row: 3 },
    { label: 'MC', position: 'MC', row: 3 },
    { label: 'MC', position: 'MC', row: 3 },
    { label: 'MR', position: 'MR', row: 3 },
    { label: 'ST', position: 'ST', row: 4 }
  ],
  '4-4-1-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'AMC', position: 'AMC', row: 3 },
    { label: 'ST', position: 'ST', row: 4 }
  ],
  '3-4-1-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'AMC', position: 'AMC', row: 3 },
    { label: 'ST', position: 'ST', row: 4 },
    { label: 'ST', position: 'ST', row: 4 }
  ],
  '4-1-2-1-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'DMC', position: 'DMC', row: 2 },
    { label: 'MC', position: 'MC', row: 3 },
    { label: 'MC', position: 'MC', row: 3 },
    { label: 'AMC', position: 'AMC', row: 4 },
    { label: 'ST', position: 'ST', row: 5 },
    { label: 'ST', position: 'ST', row: 5 }
  ],
  '5-4-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'WBL', position: 'WBL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'WBR', position: 'WBR', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'ST', position: 'ST', row: 3 }
  ],
  '4-3-2-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'AML', position: 'AML', row: 3 },
    { label: 'AMR', position: 'AMR', row: 3 },
    { label: 'ST', position: 'ST', row: 4 }
  ],
  '4-1-3-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'DMC', position: 'DMC', row: 2 },
    { label: 'AML', position: 'AML', row: 3 },
    { label: 'AMC', position: 'AMC', row: 3 },
    { label: 'AMR', position: 'AMR', row: 3 },
    { label: 'ST', position: 'ST', row: 4 },
    { label: 'ST', position: 'ST', row: 4 }
  ],
  'Custom': [
    // Row 0 (Top - Strikers): . ST ST ST .
    { label: '', position: null, row: 0, col: 0, selectable: false },
    { label: 'ST', position: 'ST', row: 0, col: 1, selectable: true },
    { label: 'ST', position: 'ST', row: 0, col: 2, selectable: true },
    { label: 'ST', position: 'ST', row: 0, col: 3, selectable: true },
    { label: '', position: null, row: 0, col: 4, selectable: false },
    // Row 1: AML AMC AMC AMC AMR
    { label: 'AML', position: 'AML', row: 1, col: 0, selectable: true },
    { label: 'AMC', position: 'AMC', row: 1, col: 1, selectable: true },
    { label: 'AMC', position: 'AMC', row: 1, col: 2, selectable: true },
    { label: 'AMC', position: 'AMC', row: 1, col: 3, selectable: true },
    { label: 'AMR', position: 'AMR', row: 1, col: 4, selectable: true },
    // Row 2: ML MC MC MC MR
    { label: 'ML', position: 'ML', row: 2, col: 0, selectable: true },
    { label: 'MC', position: 'MC', row: 2, col: 1, selectable: true },
    { label: 'MC', position: 'MC', row: 2, col: 2, selectable: true },
    { label: 'MC', position: 'MC', row: 2, col: 3, selectable: true },
    { label: 'MR', position: 'MR', row: 2, col: 4, selectable: true },
    // Row 3: WBL DMC DMC DMC WBR
    { label: 'WBL', position: 'WBL', row: 3, col: 0, selectable: true },
    { label: 'DMC', position: 'DMC', row: 3, col: 1, selectable: true },
    { label: 'DMC', position: 'DMC', row: 3, col: 2, selectable: true },
    { label: 'DMC', position: 'DMC', row: 3, col: 3, selectable: true },
    { label: 'WBR', position: 'WBR', row: 3, col: 4, selectable: true },
    // Row 4: DL DC DC DC DR
    { label: 'DL', position: 'DL', row: 4, col: 0, selectable: true },
    { label: 'DC', position: 'DC', row: 4, col: 1, selectable: true },
    { label: 'DC', position: 'DC', row: 4, col: 2, selectable: true },
    { label: 'DC', position: 'DC', row: 4, col: 3, selectable: true },
    { label: 'DR', position: 'DR', row: 4, col: 4, selectable: true },
    // Row 5 (Bottom - Goalkeeper): . . GK . .
    { label: '', position: null, row: 5, col: 0, selectable: false },
    { label: '', position: null, row: 5, col: 1, selectable: false },
    { label: 'GK', position: 'GK', row: 5, col: 2, selectable: true },
    { label: '', position: null, row: 5, col: 3, selectable: false },
    { label: '', position: null, row: 5, col: 4, selectable: false }
  ]
};