export const formations = {
  '4-4-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'ST', position: 'ST', row: 3 },
    { label: 'ST', position: 'ST', row: 3 }
  ],
  '4-3-3': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'AML', position: 'AML', row: 3 },
    { label: 'ST', position: 'ST', row: 3 },
    { label: 'AMR', position: 'AMR', row: 3 }
  ],
  '3-5-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'ST', position: 'ST', row: 3 },
    { label: 'ST', position: 'ST', row: 3 }
  ],
  '4-2-3-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'DMC', position: 'DMC', row: 2 },
    { label: 'DMC', position: 'DMC', row: 2 },
    { label: 'AML', position: 'AML', row: 3 },
    { label: 'AMC', position: 'AMC', row: 3 },
    { label: 'AMR', position: 'AMR', row: 3 },
    { label: 'ST', position: 'ST', row: 4 }
  ],
  '4-5-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'ST', position: 'ST', row: 3 }
  ],
  '3-4-3': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'AML', position: 'AML', row: 3 },
    { label: 'ST', position: 'ST', row: 3 },
    { label: 'AMR', position: 'AMR', row: 3 }
  ],
  '5-3-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'WBL', position: 'WBL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'WBR', position: 'WBR', row: 1 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'ST', position: 'ST', row: 3 },
    { label: 'ST', position: 'ST', row: 3 }
  ],
  '4-1-4-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'DMC', position: 'DMC', row: 2 },
    { label: 'ML', position: 'ML', row: 3 },
    { label: 'MC', position: 'MC', row: 3 },
    { label: 'MC', position: 'MC', row: 3 },
    { label: 'MR', position: 'MR', row: 3 },
    { label: 'ST', position: 'ST', row: 4 }
  ],
  '4-4-1-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'AMC', position: 'AMC', row: 3 },
    { label: 'ST', position: 'ST', row: 4 }
  ],
  '3-4-1-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'AMC', position: 'AMC', row: 3 },
    { label: 'ST', position: 'ST', row: 4 },
    { label: 'ST', position: 'ST', row: 4 }
  ],
  '4-1-2-1-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'DMC', position: 'DMC', row: 2 },
    { label: 'MC', position: 'MC', row: 3 },
    { label: 'MC', position: 'MC', row: 3 },
    { label: 'AMC', position: 'AMC', row: 4 },
    { label: 'ST', position: 'ST', row: 5 },
    { label: 'ST', position: 'ST', row: 5 }
  ],
  '5-4-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'WBL', position: 'WBL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'WBR', position: 'WBR', row: 1 },
    { label: 'ML', position: 'ML', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MR', position: 'MR', row: 2 },
    { label: 'ST', position: 'ST', row: 3 }
  ],
  '4-3-2-1': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'MC', position: 'MC', row: 2 },
    { label: 'AML', position: 'AML', row: 3 },
    { label: 'AMR', position: 'AMR', row: 3 },
    { label: 'ST', position: 'ST', row: 4 }
  ],
  '4-1-3-2': [
    { label: 'GK', position: 'GK', row: 0 },
    { label: 'DL', position: 'DL', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DC', position: 'DC', row: 1 },
    { label: 'DR', position: 'DR', row: 1 },
    { label: 'DMC', position: 'DMC', row: 2 },
    { label: 'AML', position: 'AML', row: 3 },
    { label: 'AMC', position: 'AMC', row: 3 },
    { label: 'AMR', position: 'AMR', row: 3 },
    { label: 'ST', position: 'ST', row: 4 },
    { label: 'ST', position: 'ST', row: 4 }
  ]
};